2019-12-09 15:46:03.618 +08 [12868] LOG:  starting PostgreSQL 12.1, compiled by Visual C++ build 1914, 64-bit
2019-12-09 15:46:03.626 +08 [12868] LOG:  listening on IPv6 address "::1", port 5432
2019-12-09 15:46:03.627 +08 [12868] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2019-12-09 15:46:03.807 +08 [2924] LOG:  database system was shut down at 2019-12-09 15:45:23 +08
2019-12-09 15:46:04.067 +08 [12868] LOG:  database system is ready to accept connections
2019-12-09 16:05:15.832 +08 [6932] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2019-12-09 16:18:52.353 +08 [16260] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2019-12-09 16:26:52.869 +08 [12868] LOG:  server process (PID 15184) was terminated by exception 0xC000013A
2019-12-09 16:26:52.869 +08 [12868] DETAIL:  Failed process was running: /*pga4dash*/
	SELECT 'session_stats' AS chart_name, row_to_json(t) AS chart_data
	FROM (SELECT
	   (SELECT count(*) FROM pg_stat_activity WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16490)) AS "Total",
	   (SELECT count(*) FROM pg_stat_activity WHERE state = 'active' AND datname = (SELECT datname FROM pg_database WHERE oid = 16490))  AS "Active",
	   (SELECT count(*) FROM pg_stat_activity WHERE state = 'idle' AND datname = (SELECT datname FROM pg_database WHERE oid = 16490))  AS "Idle"
	) t
	UNION ALL
	SELECT 'tps_stats' AS chart_name, row_to_json(t) AS chart_data
	FROM (SELECT
	   (SELECT sum(xact_commit) + sum(xact_rollback) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16490)) AS "Transactions",
	   (SELECT sum(xact_commit) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16490)) AS "Commits",
	   (SELECT sum(xact_rollback) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16490)) AS "Rollbacks"
	) 
2019-12-09 16:26:52.869 +08 [12868] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-12-09 16:26:52.870 +08 [12868] LOG:  terminating any other active server processes
2019-12-09 16:26:52.899 +08 [11360] WARNING:  terminating connection because of crash of another server process
2019-12-09 16:26:52.899 +08 [11360] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2019-12-09 16:26:52.899 +08 [11360] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2019-12-09 16:26:52.915 +08 [9788] WARNING:  terminating connection because of crash of another server process
2019-12-09 16:26:52.915 +08 [9788] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2019-12-09 16:26:52.915 +08 [9788] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2019-12-09 16:26:52.949 +08 [12868] LOG:  all server processes terminated; reinitializing
2019-12-09 16:26:53.128 +08 [15164] LOG:  database system was interrupted; last known up at 2019-12-09 15:51:05 +08
2019-12-09 16:26:53.149 +08 [15364] FATAL:  the database system is in recovery mode
2019-12-09 16:26:54.865 +08 [15164] LOG:  database system was not properly shut down; automatic recovery in progress
2019-12-09 16:26:54.898 +08 [15164] LOG:  redo starts at 0/16CE170
2019-12-09 16:26:54.899 +08 [15164] LOG:  invalid record length at 0/16CE258: wanted 24, got 0
2019-12-09 16:26:54.899 +08 [15164] LOG:  redo done at 0/16CE220
2019-12-09 16:26:55.094 +08 [16132] FATAL:  the database system is in recovery mode
2019-12-09 16:26:55.173 +08 [12868] LOG:  database system is ready to accept connections
2019-12-09 16:26:55.826 +08 [12868] LOG:  background worker "logical replication launcher" (PID 11256) was terminated by exception 0xC000013A
2019-12-09 16:26:55.826 +08 [12868] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-12-09 16:26:55.827 +08 [12868] LOG:  terminating any other active server processes
2019-12-09 16:26:55.837 +08 [15888] WARNING:  terminating connection because of crash of another server process
2019-12-09 16:26:55.837 +08 [15888] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2019-12-09 16:26:55.837 +08 [15888] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2019-12-09 16:26:55.843 +08 [12868] LOG:  statistics collector process (PID 10860) was terminated by exception 0xC000013A
2019-12-09 16:26:55.843 +08 [12868] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-12-09 16:26:55.853 +08 [12868] LOG:  all server processes terminated; reinitializing
2019-12-09 16:26:56.043 +08 [16040] LOG:  database system was interrupted; last known up at 2019-12-09 16:26:55 +08
2019-12-09 16:26:56.087 +08 [16120] FATAL:  the database system is in recovery mode
2019-12-09 16:26:57.080 +08 [16584] FATAL:  the database system is in recovery mode
2019-12-09 16:26:57.364 +08 [16040] LOG:  database system was not properly shut down; automatic recovery in progress
2019-12-09 16:26:57.400 +08 [16040] LOG:  invalid record length at 0/16CE2D0: wanted 24, got 0
2019-12-09 16:26:57.400 +08 [16040] LOG:  redo is not required
2019-12-09 16:26:57.655 +08 [12868] LOG:  database system is ready to accept connections
2019-12-09 16:27:07.758 +08 [16424] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2019-12-09 16:32:46.202 +08 [16224] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2019-12-09 16:37:04.004 +08 [12868] LOG:  server process (PID 14872) was terminated by exception 0xC000013A
2019-12-09 16:37:04.004 +08 [12868] DETAIL:  Failed process was running: /*pga4dash*/
	SELECT 'session_stats' AS chart_name, row_to_json(t) AS chart_data
	FROM (SELECT
	   (SELECT count(*) FROM pg_stat_activity WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16490)) AS "Total",
	   (SELECT count(*) FROM pg_stat_activity WHERE state = 'active' AND datname = (SELECT datname FROM pg_database WHERE oid = 16490))  AS "Active",
	   (SELECT count(*) FROM pg_stat_activity WHERE state = 'idle' AND datname = (SELECT datname FROM pg_database WHERE oid = 16490))  AS "Idle"
	) t
	UNION ALL
	SELECT 'tps_stats' AS chart_name, row_to_json(t) AS chart_data
	FROM (SELECT
	   (SELECT sum(xact_commit) + sum(xact_rollback) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16490)) AS "Transactions",
	   (SELECT sum(xact_commit) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16490)) AS "Commits",
	   (SELECT sum(xact_rollback) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16490)) AS "Rollbacks"
	) 
2019-12-09 16:37:04.004 +08 [12868] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-12-09 16:37:04.004 +08 [12868] LOG:  terminating any other active server processes
2019-12-09 16:37:04.027 +08 [17292] WARNING:  terminating connection because of crash of another server process
2019-12-09 16:37:04.027 +08 [17292] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2019-12-09 16:37:04.027 +08 [17292] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2019-12-09 16:37:04.148 +08 [12868] LOG:  statistics collector process (PID 17196) was terminated by exception 0xC000013A
2019-12-09 16:37:04.148 +08 [12868] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-12-09 16:37:04.186 +08 [16080] FATAL:  the database system is in recovery mode
2019-12-09 16:37:04.204 +08 [12868] LOG:  all server processes terminated; reinitializing
2019-12-09 16:37:04.274 +08 [17364] LOG:  database system was interrupted; last known up at 2019-12-09 16:26:57 +08
2019-12-09 16:37:05.085 +08 [13160] FATAL:  the database system is in recovery mode
2019-12-09 16:37:05.706 +08 [17364] LOG:  database system was not properly shut down; automatic recovery in progress
2019-12-09 16:37:05.730 +08 [17364] LOG:  redo starts at 0/16CE348
2019-12-09 16:37:05.731 +08 [17364] LOG:  invalid record length at 0/16CE380: wanted 24, got 0
2019-12-09 16:37:05.731 +08 [17364] LOG:  redo done at 0/16CE348
2019-12-09 16:37:06.057 +08 [12868] LOG:  database system is ready to accept connections
2019-12-09 16:37:06.327 +08 [12868] LOG:  server process (PID 12636) was terminated by exception 0xC000013A
2019-12-09 16:37:06.327 +08 [12868] DETAIL:  Failed process was running: SET DateStyle=ISO; SET client_min_messages=notice; SELECT set_config('bytea_output','escape',false) FROM pg_settings WHERE name = 'bytea_output'; SET client_encoding='WIN1252';
2019-12-09 16:37:06.327 +08 [12868] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-12-09 16:37:06.328 +08 [12868] LOG:  terminating any other active server processes
2019-12-09 16:37:06.348 +08 [12868] LOG:  statistics collector process (PID 15716) was terminated by exception 0xC000013A
2019-12-09 16:37:06.348 +08 [12868] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-12-09 16:37:06.360 +08 [12868] LOG:  all server processes terminated; reinitializing
2019-12-09 16:37:06.448 +08 [15696] LOG:  database system was interrupted; last known up at 2019-12-09 16:37:05 +08
2019-12-09 16:37:07.799 +08 [15696] LOG:  database system was not properly shut down; automatic recovery in progress
2019-12-09 16:37:07.833 +08 [15696] LOG:  invalid record length at 0/16CE3F8: wanted 24, got 0
2019-12-09 16:37:07.833 +08 [15696] LOG:  redo is not required
2019-12-09 16:37:08.102 +08 [12868] LOG:  database system is ready to accept connections
2019-12-09 16:37:11.892 +08 [12868] LOG:  background worker "logical replication launcher" (PID 16772) was terminated by exception 0xC000013A
2019-12-09 16:37:11.892 +08 [12868] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-12-09 16:37:11.894 +08 [12868] LOG:  terminating any other active server processes
2019-12-09 16:37:11.907 +08 [12868] LOG:  statistics collector process (PID 15136) was terminated by exception 0xC000013A
2019-12-09 16:37:11.907 +08 [12868] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-12-09 16:37:11.921 +08 [12868] LOG:  all server processes terminated; reinitializing
2019-12-09 16:37:12.012 +08 [17396] LOG:  database system was interrupted; last known up at 2019-12-09 16:37:07 +08
2019-12-09 16:37:13.222 +08 [17396] LOG:  database system was not properly shut down; automatic recovery in progress
2019-12-09 16:37:13.258 +08 [17396] LOG:  invalid record length at 0/16CE470: wanted 24, got 0
2019-12-09 16:37:13.258 +08 [17396] LOG:  redo is not required
2019-12-09 16:37:13.517 +08 [12868] LOG:  database system is ready to accept connections
2019-12-09 16:37:15.962 +08 [12868] LOG:  received fast shutdown request
2019-12-09 16:37:15.971 +08 [16704] ERROR:  canceling statement due to user request
2019-12-09 16:37:15.971 +08 [15912] ERROR:  canceling statement due to user request
2019-12-09 16:37:16.132 +08 [12868] LOG:  aborting any active transactions
2019-12-09 16:37:16.133 +08 [12868] LOG:  background worker "logical replication launcher" (PID 15912) exited with exit code 1
2019-12-09 16:37:16.166 +08 [16128] LOG:  shutting down
2019-12-09 16:37:16.365 +08 [12868] LOG:  database system is shut down
2019-12-09 17:05:46.912 +08 [11424] LOG:  starting PostgreSQL 12.1, compiled by Visual C++ build 1914, 64-bit
2019-12-09 17:05:46.919 +08 [11424] LOG:  listening on IPv6 address "::1", port 5432
2019-12-09 17:05:46.920 +08 [11424] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2019-12-09 17:05:47.132 +08 [17232] LOG:  database system was shut down at 2019-12-09 16:37:16 +08
2019-12-09 17:05:47.364 +08 [11424] LOG:  database system is ready to accept connections
2019-12-09 17:06:44.589 +08 [14892] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2019-12-09 18:02:02.758 +08 [18228] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2019-12-09 22:29:49.868 +08 [11424] LOG:  server process (PID 2736) was terminated by exception 0xC000013A
2019-12-09 22:29:49.868 +08 [11424] DETAIL:  Failed process was running: SELECT rolname AS refname, refclassid, deptype
	FROM pg_shdepend dep
	LEFT JOIN pg_roles r ON refclassid=1260 AND refobjid=r.oid
	WHERE dep.objid=16384::oid ORDER BY 1
2019-12-09 22:29:49.868 +08 [11424] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-12-09 22:29:49.869 +08 [11424] LOG:  terminating any other active server processes
2019-12-09 22:29:50.013 +08 [11424] LOG:  statistics collector process (PID 11376) was terminated by exception 0xC000013A
2019-12-09 22:29:50.013 +08 [11424] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2019-12-09 22:29:50.100 +08 [11424] LOG:  all server processes terminated; reinitializing
2019-12-09 22:29:50.208 +08 [19124] LOG:  database system was interrupted; last known up at 2019-12-09 17:10:47 +08
^C